name: Build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_C_FLAGS="-Wall -Werror" .
          cmake --build . --target install --parallel 4 && ctest --output-on-failure

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=~/.local .
          cmake --build . --target install --parallel 3 && ctest --output-on-failure

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: cmd
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=%cd:\=/%/install .
          cmake --build . --config Release --target install --parallel 4
          ctest -C Release --output-on-failure
